name: .NET CI

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    env:
      ConnectionStrings__DefaultConnection: ${{ secrets.ConnectionStrings__DefaultConnection }}
      Jwt__Key: ${{ secrets.Jwt__Key }}
      Jwt__Issuer: ${{ secrets.Jwt__Issuer }}
      Jwt__Audience: ${{ secrets.Jwt__Audience }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run:  dotnet restore MyFirstWebApi/MyFirstWebApi.csproj

      - name: Build
        run: dotnet build MyFirstWebApi/MyFirstWebApi.csproj --no-restore

      - name: Test
        run: dotnet test MyFirstWebApi.Tests/MyFirstWebApi.Tests.csproj